spring.application.name=bs-solutions
server.address=0.0.0.0
server.port=${PORT:8080}

# On Render, set env vars:
# - SPRING_DATASOURCE_URL (jdbc:postgresql://HOST:PORT/DB)
# - SPRING_DATASOURCE_USERNAME
# - SPRING_DATASOURCE_PASSWORD
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/forklift_db_x8il}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:forklift_db_x8il_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:oLOwogpOQmoow8btF4lSK5WP0JHtcSvD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false

spring.jackson.serialization.write-dates-as-timestamps=false

spring.jackson.serialization.fail-on-empty-beans=false

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace